var vueApp = new Vue({
    el: '#vueApp',
    data: {
        search: "Cherche...",
        searchButton: "Cherche",
        login: "Log in",
        signin: "Sign in",
        man: "Le homme",
        women: "La famme",
        boy: "Le garcon",
        girl: "La fille",
        carouselOneBigText: "Bonjour!",
        carouselOneSmallerText: "Dernière chance pour commander",
        carouselTwoBigText: "Comment ca va?",
        carouselTwoSmallerText: "Succombez à son charme",
        carouselThreeBigText: "Et toi?",
        carouselThreeSmallerText: "Le nouveau parfum Louis Vuitton",
        secondMainOneText: "La dernière collection d'été",
        secondMainTwoText: "Offre de prix",
        secondMainThreeText: "Au coeur de paris",
        welcome: "Bienvenue",
        address: "Louis Vuitton Maison Champs Élysées",
        addressSmall: "01 Av. des Champs-Élysées, 75008 Paris, France",
        mainweb: "Page d'accueil",
        contact: "Contact",
        work: "Travail",
        rodo: "RODO",
    }
});