var vueApp = new Vue({
    el: '#vueApp',
    data: {
        dog: "maja the dog",
        search: "Szukaj...",
        searchButton: "Cherdfdfdfche",
        login: "Zaloguj sie",
        signin: "Sign in",
        man: "Le homme",
        women: "La famme",
        boy: "Le garcon",
        girl: "La fille",
        carouselOneBigText: "Witamy",
        carouselOneSmallerText: "Test",
        carouselTwoBigText: "Comment ca va?",
        carouselTwoSmallerText: "Test",
        carouselThreeBigText: "Et toi?",
        carouselThreeSmallerText: "Test",
        secondMainOneText: "Test",
        secondMainTwoText: "Test",
        secondMainThreeText: "Test",
        welcome: "Bievnue",
        address: "Test",
        mainweb: "Test",
        contact: "Test",
        work: "Test",
        rodo: "RODO",
    }
});